### ISSUE TITLE
AttributeError: 'Time' object has no attribute 'toordinal'`

### ISSUE THREAD

**Issue by ghost** [helioforecast/Predstorm#7]
Hello,

I was trying to run your code but I'm getting the following error when running predstorm_l1.py: 

`Traceback (most recent call last):
  File "/gdrive/My Drive/PREDSTORM-master/predstorm_l1.py", line 148, in <module>
    [dism,dis] = get_dscovr_data_real_old()
  File "/gdrive/My Drive/PREDSTORM-master/predstorm/data.py", line 1160, in get_dscovr_data_real_old
    rbtime_num[k]=mdates.date2num(sunpy.time.parse_time(rbtime_str[k]))
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/dates.py", line 419, in date2num
    return _to_ordinalf(d)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/dates.py", line 228, in _to_ordinalf
    base = float(dt.toordinal())
  File "/usr/local/lib/python3.6/dist-packages/astropy/time/core.py", line 1556, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Time' object has no attribute 'toordinal'`

Could you please tell me how I can solve this issue? I modified the code in a few different ways but I wasn't able to solve the problem.

Thank you in advance.

**Comment by cmoestl** [comment]
Hi - I guess that you need to update either python, matplotlib or sunpy, I can run the code with:
Python 3.7.3
Matplotlib 3.1.0
sunpy 0.9.6
ciao chris

**Comment by ghost** [comment]
Hello!

Thank you for your reply. I downgraded sunpy to 0.9.6 version, and the code works perfectly well now.

By the way, I noticed a small error when I ran predstorm_l1.py for the first time.  
In line 366, you might want to change ps.get_omni_data_old() to just get_omni_data_old()  since you already imported get_omni_data_old separately at the beginning of your script.

The error:
`File "/gdrive/My Drive/PREDSTORM-master/predstorm_l1.py", line 366, in <module>
    o=ps.get_omni_data_old()
AttributeError: module 'predstorm' has no attribute 'get_omni_data_old'`

Also, in the predstorm_l5.py, you might want to define logger at the beginning of your script because I initially received an error saying 'name 'logger' is not defined'. You could add something like that: 
`logging.basicConfig(level=logging.INFO)`
`logger = logging.getLogger(__name__)`

Could you also please let me know where I can get "../catpy/DATACAT/WIND_2007to2018_HEEQ_plasma_median21.p" and  "../catpy/DATACAT/insitu_times_mdates_win_2007_2018.p" files that are used in the mfr_predict.py script?

Thank you in advance. 

Kate

**Comment by cmoestl** [comment]
Hi - thanks for the notifications! These codes are all currently under development, and we haven't put all files needed online - if you want to use them as starting point for your own publications or if you want to work with us, please drop me a note at christian.moestl@oeaw.ac.at or https://twitter.com/chrisoutofspace
ciao chris
